[[MPC]]
arch = "aarch64"
git-tree-sha1 = "244955305d2fd581945bb79d80ed94489ed0a214"
os = "macos"

    [[MPC.download]]
    sha256 = "e4582981f39a0420d3ca701943d806a1096ac2cdbb5761d89396f37ec0a0aa40"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.4.1+0/MPC.v1.4.1.aarch64-apple-darwin.tar.gz"
[[MPC]]
arch = "aarch64"
git-tree-sha1 = "57950a43c2499fbcc8d7cebeacb0d82d630894ee"
libc = "glibc"
os = "linux"

    [[MPC.download]]
    sha256 = "90c9b6747e1149f1c2f80e18934f985a029d34c29733517c2fc2c13cec65dbe6"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.4.1+0/MPC.v1.4.1.aarch64-linux-gnu.tar.gz"
[[MPC]]
arch = "aarch64"
git-tree-sha1 = "2151cfc7811402a753331832c34f025a78ce35e1"
libc = "musl"
os = "linux"

    [[MPC.download]]
    sha256 = "c50e409f4097849221b76d0457e7fc64d924ddd080f7a968c6544a7fbd198ee2"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.4.1+0/MPC.v1.4.1.aarch64-linux-musl.tar.gz"
[[MPC]]
arch = "aarch64"
git-tree-sha1 = "4061b5120a5c720871dad290714ec332f5004fce"
os = "freebsd"

    [[MPC.download]]
    sha256 = "365cb08be22b02859f2544aac52d9c1454b3f70f8d4819b3e7de3bb55c0f2858"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.4.1+0/MPC.v1.4.1.aarch64-unknown-freebsd.tar.gz"
[[MPC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6b5d5483613799416d32a58e4161d96d419c5999"
libc = "glibc"
os = "linux"

    [[MPC.download]]
    sha256 = "05d53017d52b631d4e02ed9fe22f9833a291d0daeee89a1dc580d8ed2035871e"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.4.1+0/MPC.v1.4.1.armv6l-linux-gnueabihf.tar.gz"
[[MPC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "835beed98a6a678f7b823f677181dc942ae0728f"
libc = "musl"
os = "linux"

    [[MPC.download]]
    sha256 = "c462945ea6e590cbeb8e336faff303311093b4c5ef88464d109fa3feb735c1ac"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.4.1+0/MPC.v1.4.1.armv6l-linux-musleabihf.tar.gz"
[[MPC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f7ad89b2e676742c5c787d1adffb2e5c4532dae2"
libc = "glibc"
os = "linux"

    [[MPC.download]]
    sha256 = "c7615571212bc818f4432cc4e329fb77697a44e42528d9ad95b00dc8901db3d2"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.4.1+0/MPC.v1.4.1.armv7l-linux-gnueabihf.tar.gz"
[[MPC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a1c7ba5c533fdff96fa012bab703d1f791f916ce"
libc = "musl"
os = "linux"

    [[MPC.download]]
    sha256 = "29063f3dca2fbb89c3162c476ab885de80d409e68deb2681859e27e544f7d28e"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.4.1+0/MPC.v1.4.1.armv7l-linux-musleabihf.tar.gz"
[[MPC]]
arch = "i686"
git-tree-sha1 = "059d5896be5113563410611e6522d964be03efb6"
libc = "glibc"
os = "linux"

    [[MPC.download]]
    sha256 = "525d346d1be118f674292369256a8a50d01603f40aa97b20860651c8d823c9d5"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.4.1+0/MPC.v1.4.1.i686-linux-gnu.tar.gz"
[[MPC]]
arch = "i686"
git-tree-sha1 = "f33e674ff737b6d3ef85c7aed45de3d6e9088dc9"
libc = "musl"
os = "linux"

    [[MPC.download]]
    sha256 = "ebaae9376f815e606d38afc77b185a68f74bfc333a2ff1e57203082cd81c2ee8"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.4.1+0/MPC.v1.4.1.i686-linux-musl.tar.gz"
[[MPC]]
arch = "i686"
git-tree-sha1 = "3d4263c9017f249e20adc903cfa61053b7046959"
os = "windows"

    [[MPC.download]]
    sha256 = "dedebb7bf0e27fefc75e4dcd43f57b00b6e0b62ff1192b45ae7ec33f212b094b"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.4.1+0/MPC.v1.4.1.i686-w64-mingw32.tar.gz"
[[MPC]]
arch = "powerpc64le"
git-tree-sha1 = "48dab56921e2f2036aa4371df51b4cfc1512294a"
libc = "glibc"
os = "linux"

    [[MPC.download]]
    sha256 = "5a8ab6ee57333fc22a414151365d360f0759c4c8ef8a1360ebce344810f60cd4"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.4.1+0/MPC.v1.4.1.powerpc64le-linux-gnu.tar.gz"
[[MPC]]
arch = "riscv64"
git-tree-sha1 = "e78e86b4dae9305ace4f324a377cea370818096e"
libc = "glibc"
os = "linux"

    [[MPC.download]]
    sha256 = "c83df94d843a52fc1eb9698095e578cddd847e957357848fbaf7a7d140481c57"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.4.1+0/MPC.v1.4.1.riscv64-linux-gnu.tar.gz"
[[MPC]]
arch = "x86_64"
git-tree-sha1 = "55e98d1978cf4aa57c94fb1c4acbc797720be2f1"
os = "macos"

    [[MPC.download]]
    sha256 = "f3ebf2b8e97566021f9024f552d570a91d1617133b36ab8055277a2eaf619845"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.4.1+0/MPC.v1.4.1.x86_64-apple-darwin.tar.gz"
[[MPC]]
arch = "x86_64"
git-tree-sha1 = "ec494d3d30a69a19e65026952136058e672a5ca8"
libc = "glibc"
os = "linux"

    [[MPC.download]]
    sha256 = "c94bfa5c520d35d1a911020ecd7a7ef87b484401f713e9d6eca3f7d4b7467a8e"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.4.1+0/MPC.v1.4.1.x86_64-linux-gnu.tar.gz"
[[MPC]]
arch = "x86_64"
git-tree-sha1 = "5c74a30d0e9723dc25465d4134eec3b575d55bee"
libc = "musl"
os = "linux"

    [[MPC.download]]
    sha256 = "f28956c17e72cbc5795b302382f5655bcdcad6f7b8e3952c072ca1cbfb832e69"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.4.1+0/MPC.v1.4.1.x86_64-linux-musl.tar.gz"
[[MPC]]
arch = "x86_64"
git-tree-sha1 = "c0c6cc84711c6430b452d02828a60afebe73abcd"
os = "freebsd"

    [[MPC.download]]
    sha256 = "75352e64d8aa16b23186d1f220266484e92ad6349dd5e6b2d865a71920ca12cf"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.4.1+0/MPC.v1.4.1.x86_64-unknown-freebsd.tar.gz"
[[MPC]]
arch = "x86_64"
git-tree-sha1 = "40b11cc5f95a2fc9a4f8e60846f7b61a8965e5f5"
os = "windows"

    [[MPC.download]]
    sha256 = "fd5cdcb618123575b0b3b9e1cef9caa7a817d1048a85449402498af8f3ed6866"
    url = "https://github.com/JuliaBinaryWrappers/MPC_jll.jl/releases/download/MPC-v1.4.1+0/MPC.v1.4.1.x86_64-w64-mingw32.tar.gz"
