#!/usr/bin/env python3
"""Expand methods_audit_multifile.tex into Overleaf-ready methods_audit.tex."""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PAPER = ROOT / "docs" / "paper"
if not PAPER.exists():
    PAPER = ROOT / "paper"
SOURCE = PAPER / "methods_audit_multifile.tex"
OUT = PAPER / "methods_audit.tex"
INPUT_RE = re.compile(r"^[^%\n]*\\input\{([^}]+)\}", re.MULTILINE)


def strip_proof_preamble(text: str) -> str:
    lines = []
    for line in text.splitlines():
        s = line.strip()
        if s.startswith("% !TeX root"):
            continue
        if s.startswith("% Paper 2 appendix") or s.startswith("% Paper 2:"):
            continue
        lines.append(line)
    return "\n".join(lines).strip() + "\n"


def resolve_input(base: Path, target: str) -> Path:
    p = Path(target)
    if p.suffix != ".tex":
        p = p.with_suffix(".tex")
    return (base.parent / p).resolve()


def expand_inputs(text: str, base: Path, depth: int = 0) -> str:
    if depth > 10:
        raise RuntimeError("input recursion too deep")

    def repl(match: re.Match[str]) -> str:
        target = match.group(1)
        path = resolve_input(base, target)
        if not path.exists():
            raise FileNotFoundError(f"missing input: {target} -> {path}")
        body = path.read_text(encoding="utf-8")
        if "proofs/" in target.replace("\\", "/"):
            body = strip_proof_preamble(body)
        expanded = expand_inputs(body, path, depth + 1)
        return (
            f"% === begin input: {target} ===\n"
            f"{expanded}"
            f"% === end input: {target} ===\n"
        )

    return INPUT_RE.sub(repl, text)


def main() -> int:
    if not SOURCE.exists():
        print(f"Missing {SOURCE}")
        return 1

    header = (
        "% Auto-generated by scripts/python/bundle_methods_audit.py — do not edit by hand.\n"
        "% Edit methods_audit_multifile.tex + preamble_common.tex + proofs/, then regenerate.\n"
        "% OVERLEAF: upload THIS file as main.tex — no proofs/ folder needed.\n\n"
    )
    bundled = header + expand_inputs(SOURCE.read_text(encoding="utf-8"), SOURCE)
    remaining = INPUT_RE.findall(bundled)
    OUT.write_text(bundled, encoding="utf-8")

    if remaining:
        print(f"FAIL: unresolved inputs remain: {remaining}")
        return 1

    print(f"Wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size} bytes, no external \\input)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
