#!/usr/bin/env python3
"""Expand \\input{} into a single Overleaf-ready .tex file."""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PAPER = ROOT / "paper"
SOURCE = PAPER / "mub6_karlsson_ieee.tex"
OUT_STANDALONE = PAPER / "main_standalone.tex"
OUT_MAIN = PAPER / "main.tex"
OUT_MULTIFILE = PAPER / "main_multifile.tex"
INPUT_RE = re.compile(r"^[^%\n]*\\input\{([^}]+)\}", re.MULTILINE)


def strip_proof_preamble(text: str) -> str:
    lines = []
    for line in text.splitlines():
        if line.strip().startswith("% !TeX root"):
            continue
        if line.strip().startswith("% Include from main"):
            continue
        if line.strip().startswith("% Proofs:"):
            continue
        if line.strip().startswith("% Compile as part"):
            continue
        if line.strip().startswith("% Theorem T2"):
            continue
        lines.append(line)
    return "\n".join(lines).strip() + "\n"


def resolve_input(base: Path, target: str) -> Path:
    p = Path(target)
    if p.suffix != ".tex":
        p = p.with_suffix(".tex")
    return (base.parent / p).resolve()


def expand_inputs(text: str, base: Path, depth: int = 0) -> str:
    if depth > 10:
        raise RuntimeError("input recursion too deep")

    def repl(match: re.Match[str]) -> str:
        target = match.group(1)
        path = resolve_input(base, target)
        if not path.exists():
            raise FileNotFoundError(f"missing input: {target} -> {path}")
        body = path.read_text(encoding="utf-8")
        if "proofs/" in target.replace("\\", "/"):
            body = strip_proof_preamble(body)
        expanded = expand_inputs(body, path, depth + 1)
        return f"% === begin input: {target} ===\n{expanded}% === end input: {target} ===\n"

    return INPUT_RE.sub(repl, text)


def main() -> int:
    if not SOURCE.exists():
        print(f"Missing {SOURCE}")
        return 1

    text = SOURCE.read_text(encoding="utf-8")
    header = (
        "% Auto-generated by scripts/python/bundle_paper_tex.py — do not edit by hand.\n"
        "% Edit mub6_karlsson_ieee.tex and paper/proofs/*.tex, then regenerate.\n"
        "% Overleaf: upload this file as main.tex (default) — no proofs/ folder needed.\n"
        "% Local multi-file compile: use main_multifile.tex or mub6_karlsson_ieee.tex + proofs/.\n\n"
    )
    bundled = header + expand_inputs(text, SOURCE)
    remaining = INPUT_RE.findall(bundled)
    for out_path in (OUT_STANDALONE, OUT_MAIN):
        out_path.write_text(bundled, encoding="utf-8")

    multifile_wrapper = (
        "% Local / multi-file entry (requires paper/proofs/*.tex on disk).\n"
        "% Overleaf users: compile the auto-generated main.tex instead.\n"
        "% Regenerate bundled main.tex: python scripts/python/bundle_paper_tex.py\n"
        "\\input{mub6_karlsson_ieee}\n"
    )
    OUT_MULTIFILE.write_text(multifile_wrapper, encoding="utf-8")

    if remaining:
        print(f"FAIL: unresolved inputs remain: {remaining}")
        return 1

    size = OUT_MAIN.stat().st_size
    print(
        f"Wrote {OUT_MAIN.relative_to(ROOT)} and {OUT_STANDALONE.relative_to(ROOT)} "
        f"({size} bytes, no external \\input)"
    )
    print(f"Wrote {OUT_MULTIFILE.relative_to(ROOT)} (multi-file wrapper)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
