-- Macaulay2 export: theta=0 Karlsson slice, fourth-MUB witness ideal
-- Generated by symbolic_elimination.jl 2026-08-03T15:38:49.003
R = QQ[p0,p1,p2,p3,p4,p5, phi, lam, w6];
-- w6^6 - 1 = 0; theta = 0 fixed
-- Run: eliminate({p0,p1,p2,p3,p4,p5}, ideal witness)
